apiVersion: container/v1
kind: StepContainer
inherit: ../hack/defs/aws-python
title: Describe AWS Bottlerocket instances
description: >
  This task describes the Bottlerocket instances in a given account and region.
